-- Add HTML formatting: headings, bullets, origin links (prior-art URLs)

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/avgolemono-soup/">here</a> for me.',
  ingredients = E'<ul>\n<li>Extra virgin olive oil</li>\n<li>125 ml to 250 ml (1/2 cup to 1 cup) each of finely chopped carrots, celery, green onions</li>\n<li>2 garlic cloves, finely chopped</li>\n<li>2 l (8 cups) low-sodium chicken broth</li>\n<li>250 ml (1 cup) rice</li>\n<li>Pepper</li>\n<li>2 cooked boneless poultry breast equivalent, shredded (~ 175 g – 225 g)</li>\n<li>125 ml (1/2 cup) freshly-squeezed lemon juice</li>\n<li>2 large eggs</li>\n<li>Fresh parsley for garnish (optional)</li>\n</ul>',
  instructions = E'<h3>Step 0: Soak the rice</h3>\n<p>Rinse the rice. It helps to soak the rice in water for about 15 minutes or so or until you are able to break one grain of rice easily or until the veggies are done with the sauté. The rice will cook quickly and evenly.</p>\n<h3>Step 1: Sauté the veggies</h3>\n<p>In a large Dutch oven or heavy pot, heat 15 ml (1 tbsp) olive oil on medium-high. Add the carrots, celery and green onions, toss together to sauté briefly then stir in the garlic.</p>\n<h3>Step 2: Broth and rice</h3>\n<p>Add the chicken broth and bay leaves then raise the heat to high. Once the liquid has come to a rolling boil, add the rice and pepper. Turn the heat to medium-low and simmer for 20 minutes or until the rice is tender.</p>\n<h3>Step 3: Add a bird</h3>\n<p>Now stir in the cooked, shredded poultry.</p>\n<h3>Step 4: Prepare the egg-lemon sauce</h3>\n<p>To prepare the egg-lemon sauce, in a medium bowl, whisk together the 125 ml of lemon juice and two eggs. While whisking add 2 ladles-full of the broth from the cooking pot (this helps temper the eggs). Once fully combined, add the sauce to the chicken soup and stir. Immediately remove from heat. This is your very last step in the cooking process, be sure to remove the soup from heat immediately.</p>\n<p>Garnish with fresh parsley, if you like. Serve hot with your favourite bread. Enjoy!</p>'
WHERE slug = 'avgolemono-soup';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/butterless-chicken/">here</a> for me but I changed it a fair bit to suit childish tastes and a parenting schedule. Household reviews likened it to more of a butter chicken than a curry though it has no dairy. It produces a full slow cooker of food.',
  ingredients = E'<ul>\n<li>2 large onions</li>\n<li>4 medium yams</li>\n<li>1 can of the thickest fattest coconut milk</li>\n<li>250 ml chicken stock</li>\n<li>700 ml to 900 ml tomato sauce, whatever is convenient</li>\n<li>60 ml (4 tablespoons) curry powder</li>\n<li>10 ml (2 teaspoons) salt</li>\n<li>1 large can of chickpeas</li>\n<li>1 kg chicken thighs</li>\n<li>500 ml frozen peas</li>\n<li>60 ml (4 tablespoons) lemon juice</li>\n<li>buncha cilantro (garnish)</li>\n</ul>',
  instructions = E'<p>This one suits the slow cooker. I have prepared and frozen the onion and yams, then frozen it until I was ready to deploy the meal.</p>\n<h3>Step 1: cut the onions and yams into a pot</h3>\n<p>Start with the onions. Treat them like they are on their way to becoming caramelized. While its cooking cut the yams. When the yams are all cut, add them too. Cook it!</p>\n<h3>Step 2: mush it. store it if you want</h3>\n<p>Jam the immersion blender into the pot and run that outboard all up and down and everyplace. Once it is a purée it can be slopped into a ziplock for freezing and deployment later if that suits you. Then you can come back at step 3 whenever sensible. If you are going onward right now, set the mush aside breifly.</p>\n<h3>Step 3: load the runny stuff</h3>\n<p>In the bottom of the slow cooker, whisk together coconut milk, chicken stock, tomato sauce, curry powder, and salt.</p>\n<h3>Step 4: load the less runny stuff</h3>\n<p>Plop the chickpeas and chicken into the slow cooker. Add the onion/yam mush to the slow cooker, stopping before it gets full. In my experience there needs to be 1 cm to 2 cm of space a the top to avoid spillage while cooking.</p>\n<h3>Step 5: cook that sauce</h3>\n<p>Turn the slow cooker on and ignore it for 8 hours.</p>\n<h3>Step 6: finishing touches</h3>\n<p>Add the frozen peas and lemon juice after it is done cooking. Serve over rice. Don''t forget about that cilantro.</p>'
WHERE slug = 'butterless-chicken';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/greek-potatoes/">here</a> for me; a recommendation from Colleen.',
  ingredients = E'<ul>\n<li>1 kg potatoes, peeled and cut into wedges</li>\n<li>5 ml (1 teaspoon) sea salt</li>\n<li>5 ml (1 teaspoon) baking soda</li>\n<li>6 – 10 cloves minced garlic</li>\n<li>2 heaping tbsp mustard</li>\n<li>85 ml (1/3 cup) fresh squeezed lemon juice</li>\n<li>125 ml (1/2 cup) extra virgin olive oil</li>\n<li>20 ml (1.5 tablespoons) dried oregano</li>\n<li>5 ml (1 teaspoon) ground pepper</li>\n</ul>',
  instructions = E'<p>Nearly all these steps all occur a day prior to cooking and eating the potatoes.</p>\n<h3>Step 1: cut the potatoes</h3>\n<p>Start by boiling a big pot of water on the stove and peeling your potatoes. Quarter the potatoes length-wise. If some potatoes are extra thick, you may want to cut each quarter in half.</p>\n<h3>Step 2: boil potatoes for 2 minutes in salt and soda</h3>\n<p>Once your water is boiling, add in 1 tsp of salt and 1 tsp of baking soda, then add in your potatoes and cover with a lid. Immediately, set the timer for two minutes. The cool potatoes will stop the water from boiling, but that''s okay — they are still cooking and getting softer. Once the timer goes, dump the potatoes out into a sieve and rinse with cold water to stop them from cooking further. You don''t want them too soft. Set them aside while you prepare the marinade.</p>\n<h3>Step 3: mix marinade</h3>\n<p>In your large casserole dish (anywhere around 11″ x 9″), mix together: minced garlic, yellow mustard, lemon juice, olive oil, oregano, salt and pepper.</p>\n<h3>Step 4: marinade the potatoes overnight</h3>\n<p>Add in your potatoes and stir them around until each is fully coated. Cover and place in the fridge overnight. When you have the opportunity, remove them from the fridge and stir the potatoes around so the other sides get to bathe in the marinade (do this at least three times before cooking).</p>\n<h3>Step 5: bake the potatoes at 390 °F</h3>\n<p>When it''s time to cook them, preheat your oven to 390 °F and cover the dish with an upside down baking sheet (aluminum foil is typically used here but I find a baking sheet works just as well). Bake for an hour, then remove the cover and bake for another 45 minutes. Thanks to the baking soda in the boiling water, the bottoms should have a crispy layer. Remove from oven and enjoy.</p>'
WHERE slug = 'greek-potatoes';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/lamb-meatballs/">here</a> for me; a recommendation from Lindsay. I''ve reduced the salt by 1/3. "Serves 4."',
  ingredients = E'<h4>The sauce</h4>\n<ul>\n<li>1 eggplant, cubed</li>\n<li>30 ml (2 tablespoons) olive oil</li>\n<li>salt and freshly ground black pepper to taste</li>\n<li>1/2 to 3/4 of a medium onion, minced (1/4 of the onion is in the meatballs)</li>\n<li>1 pinch crushed red pepper flakes</li>\n<li>375 ml (1 1/2 cups) chicken broth (use minimal liquid if using "better than bouillon")</li>\n<li>250 ml (1 cup) marinara sauce</li>\n</ul>\n<h4>The meatballs</h4>\n<ul>\n<li>60 ml (1/4 cup) plain dry bread crumbs</li>\n<li>1 large egg</li>\n<li>25 ml (1 1/2 tablespoons) Greek yogurt</li>\n<li>1/4 onion, finely minced</li>\n<li>4-8 cloves garlic, finely minced</li>\n<li>1 ml (1/4 teaspoon) or less kosher salt</li>\n<li>5 ml (1 teaspoon) ground pepper</li>\n<li>5 ml (1 teaspoon) ground cumin</li>\n<li>2.5 ml (1/2 teaspoon) ground cinnamon</li>\n<li>1 ml (1/4 teaspoon) ground coriander</li>\n<li>1 ml (1/4 teaspoon) cayenne pepper</li>\n<li>500 g (~1 pound) ground lamb</li>\n<li>15 ml (1 tablespoon) chopped mint</li>\n</ul>',
  instructions = E'<p>Meatballs can be made prior to the sauce, or while it simmers. Meatballs cook in the oven at 450 °F; preheat the oven now if making them in succession.</p>\n<h3>Step 1: start the sauce with the eggplant</h3>\n<p>Combine eggplant, olive oil, salt and black pepper in a large skillet over medium-high heat. Cook and stir until eggplant begins to soften, about 5 minutes.</p>\n<h3>Step 2: add onions and spices</h3>\n<p>Mix in minced onion and red pepper flakes. Reduce heat to medium; cook and stir until onion softens, 4 minutes.</p>\n<h3>Step 3: add chicken broth and marinara</h3>\n<p>Stir in chicken broth and marinara sauce. Reduce heat to medium-low and simmer until sauce mixture has reduced by half, about 30 minutes.</p>\n<h3>Step 4: start the meatballs</h3>\n<p>Line a baking sheet with parchment paper or silicone baking mats. Do it now, before your hands are meatmessy.</p>\n<p>Whisk bread crumbs, egg, and Greek yogurt in a large bowl until the bread crumbs absorb all the liquid, about 3 minutes.</p>\n<h3>Step 5: add onion and spices</h3>\n<p>Mix onions, garlic, Kosher salt, black pepper, cumin, cinnamon, coriander, and cayenne into the bread crumb mixture.</p>\n<h3>Step 6: add lamb</h3>\n<p>Crumble lamb into bread crumb spice mixture.</p>\n<h3>Step 7: form the meatballs</h3>\n<p>Form lamb mixture into small meatballs and transfer to prepared baking sheet. Place baking sheet into the preheated oven (450 °F) and bake until browned, but still pink inside, about 10 minutes.</p>\n<h3>Step 8: combine meatballs and sauce</h3>\n<p>Remove meatballs from the oven and stir into simmering sauce. Simmer over low heat until sauce begins to thicken, 30 to 45 minutes.</p>\n<p>Garnish with chopped fresh mint.</p>'
WHERE slug = 'lamb-meatballs';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/pasta-primavera/">here</a> for me.',
  ingredients = E'<ul>\n<li>Penne pasta</li>\n<li>Salt</li>\n<li>Olive oil</li>\n<li>Fresh veggies including red onion, carrot, broccoli, bell pepper, yellow squash, zucchini, tomatoes and garlic</li>\n<li>2 tsp dried Italian seasoning</li>\n<li>2 Tbsp fresh lemon juice</li>\n<li>2 Tbsp chopped fresh parsley</li>\n<li>1/2 cup shredded parmigiano, divided</li>\n</ul>',
  instructions = E'<h3>Step 0: Chop all the veggies</h3>\n<p>Probably juliennes.</p>\n<h3>Step 1: Boil the Pasta</h3>\n<p>Bring a large pot of water to a boil, add salt, then cook pasta according to package directions. Reserve 1/2 cup pasta water before draining.</p>\n<h3>Step 2: Sauté Vegetables</h3>\n<p>While the pasta is boiling cook the veggies so they will finish at the same time as the pasta.</p>\n<p>To do so, heat olive oil in a 12-inch (and deep) skillet over medium-high heat. Add red onion and carrot and sauté 2 minutes.</p>\n<p>Add broccoli and bell pepper then sauté 2 minutes. Add squash and zucchini then sauté 2 – 3 minutes or until veggies have nearly softened.</p>\n<p>Add garlic tomatoes, and Italian seasoning and sauté 2 minutes longer.</p>\n<h3>Step 3: Toss Pasta and Veggies Together with Seasonings</h3>\n<p>Pour veggies into now empty pasta pot or a serving bowl, add drained pasta, drizzle in lemon juice, season with a little more salt as needed and toss while adding in pasta water to loosen as desired.</p>\n<p>Toss in 1/4 cup parmigiano and parsley then serve with remaining parmesan on top.</p>'
WHERE slug = 'pasta-primavera';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/soft-boiled-eggs/">here</a> for me.',
  instructions = E'<h3>Step 1: boil water</h3>\n<p>Bring a pot of water to a boil with enough water to cover the eggs by about an inch.</p>\n<h3>Step 2: put in the eggs gently at a simmer</h3>\n<p>Reduce the heat to low and use a skimmer to gently place the eggs in the water. By reducing the heat to low, you''ll prevent the eggs from bouncing around and cracking. Then, turn the heat back up to a boil.</p>\n<h3>Step 3: time it!</h3>\n<p>Immediately set a timer and cook the eggs according to how soft or hard you''d like them. Here''s my general description of how long to boil eggs:</p>\n<h3>Step 4: get them out and chilled</h3>\n<p><strong>6 minutes:</strong> A liquidy yolk and soft white. This is perfect for eggs served in an egg cup.</p>\n<p><strong>6.5 minutes:</strong> A soft, jammy yolk. This is my favourite for eggs on toast or soft boiled eggs on a salad.</p>\n<p><strong>8 minutes:</strong> A soft yolk but firm enough to hold its own.</p>\n<p><strong>10 minutes:</strong> The early stages of a hard boiled egg, with just a smidge of softness in the middle.</p>\n<p><strong>12 minutes:</strong> A hard boiled egg with a lighter yolk.</p>\n<p><strong>14 minutes:</strong> Your traditional hard boiled egg with the lightest yolk and a firm white, but not overcooked.</p>\n<p>Once the eggs have cooked, immediately place them in an ice water bath to stop them from cooking and maintain your perfect texture.</p>'
WHERE slug = 'soft-boiled-eggs';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/souvlaki-marinade/">here</a> for me.',
  ingredients = E'<ul>\n<li>10 – 12 skewers</li>\n<li>1 kg chicken cut into 3 cm – 4 cm pieces</li>\n<li>10 cloves minced garlic</li>\n<li>10 ml (2 teaspoons) oregano</li>\n<li>5 ml (1 teaspoon) rosemary</li>\n<li>5 ml (1 teaspoon) paprika</li>\n<li>5 ml (1 teaspoon) salt</li>\n<li>5 ml (1 teaspoon) black pepper</li>\n<li>60 ml (1/4 cup) extra virgin olive oil</li>\n<li>60 ml (1/4 cup) lemon juice (1 lemon)</li>\n<li>Some dry white wine?</li>\n</ul>',
  instructions = E'<p>Leave the chicken in the marinade for at least 30 minutes, or overnight. Soak the skewers for 30+ minutes.</p>\n<h3>Step 1: cut the chicken</h3>\n<p>Make it into souvlaki size, probably 3 cm – 4 cm chunks.</p>\n<h3>Step 2: make the marinade</h3>\n<p>Combine all the ingredients.</p>\n<h3>Step 3: let it sit</h3>\n<p>If you didn''t take the above step literally, add the chicken to the marinade now. Set it in the fridge for 30 minutes to overnight.</p>\n<h3>Step 4: soak and poke</h3>\n<p>Soke the skewers for 30 minutes to 40 minutes. Load the skewers with chicken.</p>\n<h3>Step 5: cook</h3>\n<p>Cook the chicken then eat it. If using the BBQ on high, cooking takes about 5 minutes. Brush with more marinade during cooking if you are fancy.</p>'
WHERE slug = 'souvlaki-marinade';

UPDATE recipes SET summary = 'This recipe originates <a href="https://eatlogicalsentences.com/prior-art/thai-chicken-soup-in-the-crock-pot/">here</a> for me. Use a crock pot.',
  ingredients = E'<ul>\n<li>0.5 kg boneless, skinless chicken thighs</li>\n<li>1 yellow onion diced</li>\n<li>1 cup diagonally sliced carrots</li>\n<li>1 red bell pepper sliced</li>\n<li>1 (8 oz) package sliced mushrooms</li>\n<li>1 head broccoli cut into florets</li>\n<li>Chopped cilantro garnish</li>\n<li>Chopped peanuts garnish</li>\n<li>2 (14 oz) cans thick coconut milk</li>\n<li>3 cups chicken broth</li>\n<li>1/2 cup of the best peanut butter</li>\n<li>1 (4 oz) jar red curry paste start with 1/4 cup and add more to taste</li>\n<li>2 tablespoons fish sauce</li>\n<li>5 tablespoons tamari</li>\n<li>2 tablespoons dark brown sugar</li>\n<li>4 cloves garlic minced or pressed</li>\n<li>1 teaspoon ground ginger</li>\n<li>3 tablespoons lime juice</li>\n<li>Brown rice or noodles for serving</li>\n</ul>',
  instructions = E'<h3>Step 0: Chop all the plants and animals</h3>\n<p>This is prep. Don''t put this in the pot yet.</p>\n<p>Onions diced, carrots diag''ed, bell pepper sliced, mushrooms sliced, broccoli floretted. If your kids are like mine, blend the onions and broccoli stalks to evade their power-play.</p>\n<p>Chop the cilantro and peanuts to garnish with in about 8 hours.</p>\n<p>Slice the chicken thighs into narrow strips. (0.5 cm &lt; width &lt; 1.0 cm.)</p>\n<h3>Step 1: Add non-solids</h3>\n<p>Grease the crockpot.</p>\n<p>Whisk together sauce in crockpot: coconut milk, chicken broth, peanut butter, red curry paste, fish sauce, tamari, dark brown sugar, garlic, and ground ginger. If any of those plants ended up in the blender, mix them in now too.</p>\n<h3>Step 2: Add solids</h3>\n<p>Add in the goodies: chicken breasts, onion, carrots, bell pepper, mushrooms, and broccoli.</p>\n<h3>Step 3: Crock and go</h3>\n<p>Cover and cook on low. Come back in lotsa hours.</p>\n<h3>Step 4: Serve</h3>\n<p>It goes well with rice.</p>\n<p>It''s probably hotter''n hades – get that soup cooling somewhere.</p>\n<p>Add the 3 tablespoons of lime juice.</p>\n<p>Put the cilantro and peanuts out in fancy little bowls.</p>'
WHERE slug = 'thai-chicken-soup';
