-- Drop example recipe; add Farro Salad (rewritten in site style, origin: Grok)
DELETE FROM recipes WHERE slug = 'example-recipe';

INSERT INTO recipes (slug, title, summary, ingredients, instructions)
VALUES (
  'farro-salad',
  'Farro Salad',
  'This recipe originates with Grok. Scaled for 6 (4 adults + 2 kids). Hearty side, pairs well with pea soup.',
  E'<ul>\n<li>1 ½ cups (about 300 g) pearled or semi-pearled farro</li>\n<li>3 ¾ cups water or vegetable broth (broth for extra flavor)</li>\n<li>1 tsp salt (for cooking farro)</li>\n<li>2 cups (about 400 g) cherry or grape tomatoes, halved</li>\n<li>1 large cucumber (or 2 medium), diced (about 2 cups)</li>\n<li>½ medium red onion, finely diced (or 1 small shallot for milder)</li>\n<li>¾ cup chopped fresh parsley (about 1 big handful)</li>\n<li>¼–½ cup chopped fresh mint (optional but good)</li>\n<li>¾–1 cup crumbled feta (about 150–200 g); less if kids prefer milder</li>\n<li>½ cup pitted and halved Kalamata olives (optional, or milder black olives)</li>\n<li>2 large lemons (juice and zest; about 6–8 tbsp juice)</li>\n<li>80 ml (⅓ cup) extra-virgin olive oil</li>\n<li>1–2 cloves garlic, minced (or ½ tsp garlic powder)</li>\n<li>1–2 tsp Dijon mustard (optional)</li>\n<li>Salt and black pepper to taste</li>\n<li>Optional add-ins (pick 1–2):\n<ul>\n<li>1 cup cooked chickpeas or white beans, rinsed</li>\n<li>½ cup toasted pine nuts or slivered almonds</li>\n<li>1–2 cups arugula or baby spinach (fold in at end)</li>\n</ul>\n</li>\n</ul>',
  E'<h3>Step 1: Cook the farro</h3>\n<p>Rinse the farro under cold water. In a medium pot, bring water or broth and 1 tsp salt to a boil. Add farro, reduce to a simmer, cover partially, and cook 20–30 minutes until tender but chewy (pearled is usually 20–25 min; check the package). Drain any excess liquid and let cool slightly. Spread on a baking sheet if you need it to cool faster.</p>\n<h3>Step 2: Make the dressing</h3>\n<p>In a small bowl or jar, whisk together: juice and zest of the 2 lemons, olive oil, minced garlic, Dijon (if using), ½ tsp salt, ¼ tsp black pepper. Taste and adjust—more lemon for brightness or more oil if too sharp.</p>\n<h3>Step 3: Assemble the salad</h3>\n<p>In a large bowl, combine cooled farro, halved tomatoes, diced cucumber, red onion, parsley, mint, olives, and feta. If using chickpeas, beans, or nuts, add them now.</p>\n<h3>Step 4: Dress and finish</h3>\n<p>Pour most of the dressing over and toss gently to coat. Taste and add more dressing, salt, pepper, or lemon as needed. If using arugula or spinach, fold it in last so it doesn’t wilt.</p>\n<h3>Step 5: Serve</h3>\n<p>Best at room temperature or slightly chilled. Keeps well for leftovers (fridge up to 3 days); add a little extra lemon or dressing when you eat it again if it’s dried out.</p>'
)
ON CONFLICT (slug) DO NOTHING;
