-- Proper units (minutes, seconds—no min/sec); quantity style = lamb meatballs (metric first, teaspoon/tablespoon/cup in parentheses).
-- Chocolate mousse: remove butter and coffee.

UPDATE recipes SET ingredients = E'<ul>\n<li>100 g dark chocolate (60–70% cocoa), chopped</li>\n<li>165–170 ml heavy cream (35%+ whipping cream) total:\n<ul>\n<li>80–85 ml for melting with the chocolate</li>\n<li>80–85 ml for whipping</li>\n</ul>\n</li>\n<li>15–30 g (1–2 tablespoons) powdered sugar, divided</li>\n<li>2.5–4 ml (½–¾ teaspoon) vanilla extract</li>\n<li>Optional: tiny pinch of salt</li>\n</ul>',
  instructions = E'<h3>Step 1: Melt the chocolate</h3>\n<p>Melt chocolate in a double boiler or microwave (20-second bursts, stir often). When smooth, stir in the 80–85 ml cream and vanilla. Add optional salt if using. Let cool to room temperature or just slightly warm—so it doesn’t seize when you fold later.</p>\n<h3>Step 2: Whip the cream</h3>\n<p>In a separate bowl, whip the remaining 80–85 ml cream with 15–30 g (1–2 tablespoons) powdered sugar to stiff peaks (glossy, holds shape; don’t overwhip).</p>\n<h3>Step 3: Fold together</h3>\n<p>Gently fold the whipped cream into the cooled chocolate in 2–3 additions. Light folds with a spatula to keep it airy—don’t stir hard or it’ll deflate.</p>\n<h3>Step 4: Chill</h3>\n<p>Spoon or pipe into small glasses, ramekins, or bowls. Refrigerate at least 2 hours (4+ hours or overnight is better) until set.</p>\n<h3>Step 5: Serve</h3>\n<p>Let sit 5–10 minutes at room temp if very firm. Top with extra whipped cream, berries, shaved chocolate, or mint if you like.</p>'
WHERE slug = 'chocolate-mousse';

UPDATE recipes SET ingredients = E'<ul>\n<li>125 ml (½ cup) fresh lemon juice (about 3–4 large lemons; zest 2 of them)</li>\n<li>80 ml (⅓ cup) olive oil</li>\n<li>60–80 ml (¼–⅓ cup) chopped fresh dill (big handful)</li>\n<li>60 ml (¼ cup) chopped fresh parsley</li>\n<li>30–45 ml (2–3 tablespoons) chopped fresh basil (or more parsley/dill if no basil)</li>\n<li>4–5 cloves garlic, minced (or 5–7 ml (1–1½ teaspoons) garlic powder)</li>\n<li>5–10 ml (1–2 teaspoons) Dijon mustard (optional)</li>\n<li>5–7 ml (1–1½ teaspoons) salt (to taste)</li>\n<li>2.5–5 ml (½–1 teaspoon) freshly ground black pepper</li>\n<li>Optional: 5 ml (1 teaspoon) honey or a pinch of sugar</li>\n</ul>',
  instructions = E'<h3>Step 1: Make the marinade</h3>\n<p>Whisk all marinade ingredients together in a bowl or jar.</p>\n<h3>Step 2: Marinate the thighs</h3>\n<p>Put thighs in a large zip-top bag or shallow dish. Pour marinade over, toss to coat. Seal and refrigerate 2–8 hours (4 hours is ideal; don’t go over 12 or the lemon can "cook" the chicken).</p>\n<h3>Step 3: Cook</h3>\n<p><strong>Grill/BBQ:</strong> Medium-high heat, 6–8 minutes per side until 165 °F (74 °C) internal.</p>\n<p><strong>Oven:</strong> 425 °F (220 °C), 35–45 minutes on a lined sheet (flip halfway; broil last 2–3 minutes for crisp).</p>\n<p><strong>Pan-sear:</strong> Medium-high with a bit of oil, 6–7 minutes per side.</p>\n<p>Rest 5 minutes before serving. Discard used marinade or boil it if you want a sauce.</p>'
WHERE slug = 'lemon-dill-marinade-chicken-thighs';

UPDATE recipes SET ingredients = E'<ul>\n<li>300 g (1 ½ cups) pearled or semi-pearled farro</li>\n<li>900 ml (3 ¾ cups) water or vegetable broth (broth for extra flavor)</li>\n<li>5 ml (1 teaspoon) salt (for cooking farro)</li>\n<li>400 g (2 cups) cherry or grape tomatoes, halved</li>\n<li>1 large cucumber (or 2 medium), diced (about 500 ml / 2 cups)</li>\n<li>½ medium red onion, finely diced (or 1 small shallot for milder)</li>\n<li>180 ml (¾ cup) chopped fresh parsley (about 1 big handful)</li>\n<li>60–125 ml (¼–½ cup) chopped fresh mint (optional but good)</li>\n<li>180–250 ml (¾–1 cup) crumbled feta (about 150–200 g); less if kids prefer milder</li>\n<li>125 ml (½ cup) pitted and halved Kalamata olives (optional, or milder black olives)</li>\n<li>2 large lemons (juice and zest; about 90–120 ml / 6–8 tablespoons juice)</li>\n<li>80 ml (⅓ cup) extra-virgin olive oil</li>\n<li>1–2 cloves garlic, minced (or 2.5 ml (½ teaspoon) garlic powder)</li>\n<li>5–10 ml (1–2 teaspoons) Dijon mustard (optional)</li>\n<li>Salt and black pepper to taste</li>\n<li>Optional add-ins (pick 1–2):\n<ul>\n<li>250 ml (1 cup) cooked chickpeas or white beans, rinsed</li>\n<li>125 ml (½ cup) toasted pine nuts or slivered almonds</li>\n<li>250–500 ml (1–2 cups) arugula or baby spinach (fold in at end)</li>\n</ul>\n</li>\n</ul>',
  instructions = E'<h3>Step 1: Cook the farro</h3>\n<p>Rinse the farro under cold water. In a medium pot, bring water or broth and 5 ml (1 teaspoon) salt to a boil. Add farro, reduce to a simmer, cover partially, and cook 20–30 minutes until tender but chewy (pearled is usually 20–25 minutes; check the package). Drain any excess liquid and let cool slightly. Spread on a baking sheet if you need it to cool faster.</p>\n<h3>Step 2: Make the dressing</h3>\n<p>In a small bowl or jar, whisk together: juice and zest of the 2 lemons, olive oil, minced garlic, Dijon (if using), 2.5 ml (½ teaspoon) salt, 1.25 ml (¼ teaspoon) black pepper. Taste and adjust—more lemon for brightness or more oil if too sharp.</p>\n<h3>Step 3: Assemble the salad</h3>\n<p>In a large bowl, combine cooled farro, halved tomatoes, diced cucumber, red onion, parsley, mint, olives, and feta. If using chickpeas, beans, or nuts, add them now.</p>\n<h3>Step 4: Dress and finish</h3>\n<p>Pour most of the dressing over and toss gently to coat. Taste and add more dressing, salt, pepper, or lemon as needed. If using arugula or spinach, fold it in last so it doesn’t wilt.</p>\n<h3>Step 5: Serve</h3>\n<p>Best at room temperature or slightly chilled. Keeps well for leftovers (fridge up to 3 days); add a little extra lemon or dressing when you eat it again if it’s dried out.</p>'
WHERE slug = 'farro-salad';

UPDATE recipes SET instructions = E'<p>Nearly all these steps all occur a day prior to cooking and eating the potatoes.</p>\n<h3>Step 1: cut the potatoes</h3>\n<p>Start by boiling a big pot of water on the stove and peeling your potatoes. Quarter the potatoes length-wise. If some potatoes are extra thick, you may want to cut each quarter in half.</p>\n<h3>Step 2: boil potatoes for 2 minutes in salt and soda</h3>\n<p>Once your water is boiling, add in 5 ml (1 teaspoon) salt and 5 ml (1 teaspoon) baking soda, then add in your potatoes and cover with a lid. Immediately, set the timer for two minutes. The cool potatoes will stop the water from boiling, but that''s okay — they are still cooking and getting softer. Once the timer goes, dump the potatoes out into a sieve and rinse with cold water to stop them from cooking further. You don''t want them too soft. Set them aside while you prepare the marinade.</p>\n<h3>Step 3: mix marinade</h3>\n<p>In your large casserole dish (anywhere around 11″ x 9″), mix together:</p>\n<ul>\n<li>minced garlic</li>\n<li>yellow mustard</li>\n<li>lemon juice</li>\n<li>olive oil</li>\n<li>oregano</li>\n<li>salt and pepper</li>\n</ul>\n<h3>Step 4: marinade the potatoes overnight</h3>\n<p>Add in your potatoes and stir them around until each is fully coated. Cover and place in the fridge overnight. When you have the opportunity, remove them from the fridge and stir the potatoes around so the other sides get to bathe in the marinade (do this at least three times before cooking).</p>\n<h3>Step 5: bake the potatoes at 390 °F</h3>\n<p>When it''s time to cook them, preheat your oven to 390 °F and cover the dish with an upside down baking sheet (aluminum foil is typically used here but I find a baking sheet works just as well). Bake for an hour, then remove the cover and bake for another 45 minutes. Thanks to the baking soda in the boiling water, the bottoms should have a crispy layer. Remove from oven and enjoy.</p>'
WHERE slug = 'greek-potatoes';

UPDATE recipes SET ingredients = E'<ul>\n<li>1 kg potatoes, peeled and cut into wedges</li>\n<li>5 ml (1 teaspoon) sea salt</li>\n<li>5 ml (1 teaspoon) baking soda</li>\n<li>6 – 10 cloves minced garlic</li>\n<li>30 ml (2 heaping tablespoons) mustard</li>\n<li>85 ml (1/3 cup) fresh squeezed lemon juice</li>\n<li>125 ml (1/2 cup) extra virgin olive oil</li>\n<li>20 ml (1.5 tablespoons) dried oregano</li>\n<li>5 ml (1 teaspoon) ground pepper</li>\n</ul>'
WHERE slug = 'greek-potatoes';

UPDATE recipes SET ingredients = E'<ul>\n<li>Penne pasta</li>\n<li>Salt</li>\n<li>Olive oil</li>\n<li>Fresh veggies including red onion, carrot, broccoli, bell pepper, yellow squash, zucchini, tomatoes and garlic</li>\n<li>10 ml (2 teaspoons) dried Italian seasoning</li>\n<li>30 ml (2 tablespoons) fresh lemon juice</li>\n<li>30 ml (2 tablespoons) chopped fresh parsley</li>\n<li>125 ml (1/2 cup) shredded parmigiano, divided</li>\n</ul>'
WHERE slug = 'pasta-primavera';

UPDATE recipes SET ingredients = E'<ul>\n<li>500 g boneless, skinless chicken thighs</li>\n<li>1 yellow onion diced</li>\n<li>250 ml (1 cup) diagonally sliced carrots</li>\n<li>1 red bell pepper sliced</li>\n<li>1 (227 g / 8 oz) package sliced mushrooms</li>\n<li>1 head broccoli cut into florets</li>\n<li>Chopped cilantro garnish</li>\n<li>Chopped peanuts garnish</li>\n<li>2 (400 ml / 14 oz) cans thick coconut milk</li>\n<li>750 ml (3 cups) chicken broth</li>\n<li>125 ml (1/2 cup) of the best peanut butter</li>\n<li>1 (113 g / 4 oz) jar red curry paste start with 60 ml (1/4 cup) and add more to taste</li>\n<li>30 ml (2 tablespoons) fish sauce</li>\n<li>75 ml (5 tablespoons) tamari</li>\n<li>30 ml (2 tablespoons) dark brown sugar</li>\n<li>4 cloves garlic minced or pressed</li>\n<li>5 ml (1 teaspoon) ground ginger</li>\n<li>45 ml (3 tablespoons) lime juice</li>\n<li>Brown rice or noodles for serving</li>\n</ul>',
  instructions = E'<h3>Step 0: Chop all the plants and animals</h3>\n<p>This is prep. Don''t put this in the pot yet.</p>\n<p>Onions diced, carrots diag''ed, bell pepper sliced, mushrooms sliced, broccoli floretted. If your kids are like mine, blend the onions and broccoli stalks to evade their power-play.</p>\n<p>Chop the cilantro and peanuts to garnish with in about 8 hours.</p>\n<p>Slice the chicken thighs into narrow strips. (0.5 cm &lt; width &lt; 1.0 cm.)</p>\n<h3>Step 1: Add non-solids</h3>\n<p>Grease the crockpot.</p>\n<p>Whisk together sauce in crockpot: coconut milk, chicken broth, peanut butter, red curry paste, fish sauce, tamari, dark brown sugar, garlic, and ground ginger. If any of those plants ended up in the blender, mix them in now too.</p>\n<h3>Step 2: Add solids</h3>\n<p>Add in the goodies: chicken breasts, onion, carrots, bell pepper, mushrooms, and broccoli.</p>\n<h3>Step 3: Crock and go</h3>\n<p>Cover and cook on low. Come back in lotsa hours.</p>\n<h3>Step 4: Serve</h3>\n<p>It goes well with rice.</p>\n<p>It''s probably hotter''n hades – get that soup cooling somewhere.</p>\n<p>Add the 45 ml (3 tablespoons) of lime juice.</p>\n<p>Put the cilantro and peanuts out in fancy little bowls.</p>'
WHERE slug = 'thai-chicken-soup';

UPDATE recipes SET instructions = E'<h3>Step 0: Soak the rice</h3>\n<p>Rinse the rice. It helps to soak the rice in water for about 15 minutes or so or until you are able to break one grain of rice easily or until the veggies are done with the sauté. The rice will cook quickly and evenly.</p>\n<h3>Step 1: Sauté the veggies</h3>\n<p>In a large Dutch oven or heavy pot, heat 15 ml (1 tablespoon) olive oil on medium-high. Add the carrots, celery and green onions, toss together to sauté briefly then stir in the garlic.</p>\n<h3>Step 2: Broth and rice</h3>\n<p>Add the chicken broth and bay leaves then raise the heat to high. Once the liquid has come to a rolling boil, add the rice and pepper. Turn the heat to medium-low and simmer for 20 minutes or until the rice is tender.</p>\n<h3>Step 3: Add a bird</h3>\n<p>Now stir in the cooked, shredded poultry.</p>\n<h3>Step 4: Prepare the egg-lemon sauce</h3>\n<p>To prepare the egg-lemon sauce, in a medium bowl, whisk together the 125 ml of lemon juice and two eggs. While whisking add 2 ladles-full of the broth from the cooking pot (this helps temper the eggs). Once fully combined, add the sauce to the chicken soup and stir. Immediately remove from heat. This is your very last step in the cooking process, be sure to remove the soup from heat immediately.</p>\n<p>Garnish with fresh parsley, if you like. Serve hot with your favourite bread. Enjoy!</p>'
WHERE slug = 'avgolemono-soup';
